apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  cluster-pods.json: |
    {
      "title": "Cluster Monitoring",
      "uid": "cluster-pods",
      "schemaVersion": 39,
      "version": 10,
      "refresh": "5s",
      "panels": [
        {
          "title": "Prometheus Target Health",
          "type": "timeseries",
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "targets": [
            {
              "expr": "up",
              "legendFormat": "{{job}} - {{instance}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 0
          }
        },
        {
          "title": "CPU Usage Raw",
          "type": "timeseries",
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "targets": [
            {
              "expr": "container_cpu_usage_seconds_total",
              "legendFormat": "{{id}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "title": "Memory Usage Raw",
          "type": "timeseries",
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "targets": [
            {
              "expr": "container_memory_usage_bytes",
              "legendFormat": "{{id}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        }
      ]
    }
