apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: homeoffice
  POSTGRES_PASSWORD: homeoffice123
  POSTGRES_DB: homeoffice_db